import { apiClient } from '@/api/client';
import { toAppError } from '@/api/errors';
import type { Order } from '@/types/models';

/**
 * `POST /checkout` recalculates price/stock/totals server-side and creates
 * the Order — the cart is never authoritative. `idempotencyKey` must be
 * generated by the caller BEFORE the first attempt (uuidv4()) and reused on
 * every retry of the same checkout attempt, so a network timeout can never
 * create two orders.
 */
export async function checkout(idempotencyKey: string): Promise<Order> {
  try {
    const { data } = await apiClient.post<{ data: Order }>(
      'checkout',
      {},
      { headers: { 'Idempotency-Key': idempotencyKey } },
    );
    return data.data;
  } catch (error) {
    throw toAppError(error);
  }
}
